### Listar Productos
GET http://127.0.0.1:3000/api/v1/producto?page=1&limit=10&q=
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJhZG1pbkBtYWlsLmNvbSIsInRpbWUiOiIyMDI1LTAzLTE0VDAxOjQ1OjU1LjEzNVoiLCJpYXQiOjE3NDE5MTY3NTUsImV4cCI6MTc0MTkyMDM1NX0.yL96AKVGAQjnNvTDjBz9_VPYtsVD0JcbhzDvliKoWJw

### Guardar producto
POST http://127.0.0.1:3000/api/v1/producto
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJhZG1pbkBtYWlsLmNvbSIsInRpbWUiOiIyMDI1LTAzLTE0VDAxOjQ1OjU1LjEzNVoiLCJpYXQiOjE3NDE5MTY3NTUsImV4cCI6MTc0MTkyMDM1NX0.yL96AKVGAQjnNvTDjBz9_VPYtsVD0JcbhzDvliKoWJw
Content-Type: application/json

{
    "nombre": "PARLANTES",
    "precio": 956.98,
    "stock": 12,
    "descripcion": "Parlantes de Prueba",
    "categoriaId": 2
}

### 