### Listar Productos
GET http://127.0.0.1:3000/api/v1/producto?page=1&limit=3&q=
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJhZG1pbkBtYWlsLmNvbSIsInRpbWUiOiIyMDI1LTAzLTI2VDAxOjIxOjE1LjA0NVoiLCJpYXQiOjE3NDI5NTIwNzUsImV4cCI6MTc0Mjk1NTY3NX0.lNBFaBJuIzNEW5dJ1wmw8EyPUkBLXB6ogKqfuYNJHF4

### Guardar producto
POST http://127.0.0.1:3000/api/v1/producto
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJhZG1pbkBtYWlsLmNvbSIsInRpbWUiOiIyMDI1LTAzLTI2VDAxOjIxOjE1LjA0NVoiLCJpYXQiOjE3NDI5NTIwNzUsImV4cCI6MTc0Mjk1NTY3NX0.lNBFaBJuIzNEW5dJ1wmw8EyPUkBLXB6ogKqfuYNJHF4
Content-Type: application/json

{
    "nombre": "TECLADO MECANICO 2",
    "precio": 756.98,
    "stock": 20,
    "categoriaId": 2
}

### 