GET http://127.0.0.1:3000/api/v1/usuario
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJhZG1pbjJAbWFpbC5jb20iLCJ0aW1lIjoiMjAyNS0wMi0yMVQwMjoyMDozMy4yNzlaIiwiaWF0IjoxNzQwMTA0NDMzLCJleHAiOjE3NDAxMDgwMzN9.69Buo6ck5BltX4ldiJlP95v_6qD3sVRaOVTvc_CYXiY
